on:
  push:
    branches:
      - "*"


  pull_request:
    branches:
    - 'main'

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      
      - name: Eslint
        run: pnpm lint  
      - name: Unit Test
        run: pnpm test-with-coverage
      - name: Build
        run: pnpm build  